### ISSUE TITLE
OpenAPI 2.0: All parameter types are heaped into single bucket during request validation

### ISSUE THREAD

**Issue by brandur** [interagent/committee#106]
Currently when unpacking a request Committee heaps all parameters from a request no matter their type, form, body, query, or URL, into a single bucket and then performs validation against them.

This doesn't work too badly, but we should really be respecting the `in` value of an OpenAPI definition (e.g. `in: query`) so that if a parameter is meant to be in the query, a form parameter of the same name will not suffice.

**Comment by brandur** [comment]
Also, ideally this should be fixed before the initial 2.0.0 release so that fixing in later won't be a breaking change.

**Comment by hlascelles** [comment]
This may have just bitten us too. Tell me if this is the same thing...

We have a POST body that has no `id`, but the path is `/foo/{id}/bar`. During validation the path `id` is merged into the body, and we get:

`Failed schema #/properties/v3/foo/{id}/bar/properties/POST: \"id\" is not a permitted key."`

Our hack thus far is to set: `coerce_path_params: false` so that [this line](https://github.com/interagent/committee/blob/master/lib/committee/schema_validator/hyper_schema.rb#L16) does not fire.

Are we missing out on much by setting `coerce_path_params: false`?

**Comment by hlascelles** [comment]
Having done that we started getting errors on our other paths that had no body but did have path params.

In the end we had to remove `committee` from being in our middleware and invoke it directly from a Rails action `before_filter`/`before_action`:

```
VALIDATION_DRIVER = Committee::Drivers.load_from_file(Banco::Api::SWAGGER_FILE_PATH)

# The filter
private def validate_request_payload
  router = VALIDATION_DRIVER.build_router(coerce_path_params: request.method != "POST")
  router.build_schema_validator(request).request_validate(request)
end
```

It works great, but it's not so intuitive. Are we missing something?

**Comment by jalyna** [comment]
I'm also facing a problem here when I define a `requestBody` and an additional `path` parameter (with different names). This always results in an error since it seems to validate `params` and of course the path param is not a part of it:

> post/requestBody/content/application~1json/schema does not define properties: organization_id

Not sure if this is related.

**Comment by hlascelles** [comment]
@ota42y @datbth I *think* you may be committee members... This is still an issue (we believe).

It will be a breaking change, depending on how it is done. What do you think?

**Comment by ota42y** [comment]
Rails provide `params` method and it return merged parameter so when we send `/api/users/:id` with {"id": 42}, rails override `id`.
Probably the same result, but how do you use them properly?
If the behavior is different, we need to change same or other options, so I would like to know what kind of result you are expecting.

**Comment by hlascelles** [comment]
It is possible to access the GET or POST params separately thus: `request.GET` `request.POST`, so it would be possible to determine if the path or the payload have the right "keys".

Do the examples above provide enough to go on, or would a PR with a failing spec help?

**Comment by ota42y** [comment]
Ok, I understand.

I think it is better to save request_parameter, query_parameter, and path_parameter to different keys like `committee.request_params`, `committee.query_params`...
And we merge all data to one key for `committee.params` because we can get data from `request.GET()` and `request.params` in Rails, so I think it's better to get it from both.

**Comment by geemus** [comment]
I believe from reading issues that this was resolved by #349. Please let us know if I've misunderstood or there are aspects that remain to be fixed.
